version: "3"
#version of the docker compose
services:
  app:
    image: amershl/attendance-project:latest
    links: 
      - db
#port forwarding 
    ports:
      - "5000:5000"
  db:
     image: mysql:latest
     ports: 
       - "3306:3306"
     environment:
#my user is : root
       MYSQL_ROOT_PASSWORD: "${PASSWORD_MYSQL}"       
     volumes: 
       - ./db:/docker-entrypoint-initdb.d/:ro  
