version: "3"
services:
  app:
    image: attendance_image 
    links: 
      - db
    ports:
      - "5000:5000"
  db:
     image: mysql:latest
     ports: 
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: "amershala"       
     volumes: 
       - ./db:/docker-entrypoint-initdb.d/:ro  
